name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - run: npm install -g pnpm
      - run: pnpm install
    #   - run: pnpm lint
    #   - run: pnpm check
      - run: pnpm run build